<?php

namespace ShaoZeMing\AliOss\Services;


use OSS\OssClient;

class OSSService extends OssClient
{


    /**
     *
     */
    public $config;
    /**
     * @var
     */
    public $accessKeyID;
    /**
     * @var
     */
    public $accessKeySecret;
    /**
     * @var
     */
    public $endpoint;
    /**
     * @var
     */
    public $isCName;

    /**
     * @var
     */
    public $bucket;
    /**
     * @var
     */
    public $isSsl;

    /**
     * @var
     */
    public $timeout;


    /**
     * OSSService constructor.
     * @param null $config
     * @param null $securityToken
     * @param null $requestProxy
     * @throws \OSS\Core\OssException
     */
    public function __construct($config = null, $securityToken = null, $requestProxy = null)
    {

        $this->setConfig($config);

        parent::__construct($this->accessKeyID, $this->accessKeySecret, $this->endpoint, $this->isCName, $securityToken, $requestProxy);

    }


    /**
     * User: ZeMing Shao
     * Email: szm19920426@gmail.com
     * @param $config
     */
    public function setConfig($config)
    {

        $this->config = $config ?: include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'config.php';
        $this->accessKeyID = $this->config['oss']['AccessKeyID'];
        $this->accessKeySecret = $this->config['oss']['AccessKeySecret'];
        $this->endpoint = $this->config['oss']['endpoint'];
        $this->bucket = $this->config['oss']['bucket'];
        $this->isCName = $this->config['oss']['is_cname'];
        $this->isSsl = $this->config['oss']['is_ssl'];
        $this->timeout = $this->config['oss']['timeout'];
    }


    /**
     * 动态设置 bucket，不使用默认配置bucket
     * User: ZeMing Shao
     * Email: szm19920426@gmail.com
     * @param $bucket
     * @return $this
     */
    public function setBucket($bucket){

        $this->bucket=$bucket;
        return $this;
    }


    /**
     * 上传内存文件
     * User: ZeMing Shao
     * Email: szm19920426@gmail.com
     * @param $object
     * @param $content
     * @param null $options
     * @return null
     */
    public function mingPutObject($object, $content, $options = NULL)
    {
        $bucket = $this->bucket;
        return $this->putObject($bucket, $object, $content, $options); // TODO: Change the autogenerated stub
    }


    /**
     * 上传本地文件
     * User: ZeMing Shao
     * Email: szm19920426@gmail.com
     * @param string $object
     * @param string $file
     * @param null $options
     * @return null
     * @throws \OSS\Core\OssException
     */
    public function mingUploadFile($object, $file, $options = NULL)
    {
        $bucket = $this->bucket;
        return $this->uploadFile($bucket, $object, $file, $options); // TODO: Change the autogenerated stub
    }

}
